[[plugins]]
repo = 'baabelfish/nvim-nim'
on_ft = ['nim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_fmt_command = "goimports"

  let g:go_def_mapping_enabled = 0
  let g:go_doc_keywordprg_enabled = 0
'''
