[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'cohama/lexima.vim'

#[[plugins]]
#repo = 'autozimu/LanguageClient-neovim'
#rev = 'next'
## on_event = 'InsertEnter'
#depends = ['deoplete.nvim']
#build = 'bash install.sh'
#hook_source = '''
#set completefunc=LanguageClient#complete
#'''
#hook_add = '''
#set hidden
#let g:LanguageClient_serverCommands = {
#      \ 'c': ['clangd'],
#      \ 'cpp': ['clangd'],
#      \ 'rust': ['rustup', 'run', 'nightly', 'rls'],
#      \ 'd': ['dls'],
#      \ 'javascript': ['javascript-typescript-stdio'],
#      \ 'python': ['pyls'],
#      \ 'ruby': ['solargraph'],
#      \ }
#let g:LanguageClient_loadSettings = 1
#let g:LanguageClient_hasSnippetSupport = 0
#let g:LanguageClient_settingsPath = expand('$HOME/.config/nvim/LanguageClientSetting.json')
#nnoremap K :call LanguageClient#textDocument_hover()<CR>
#nnoremap gd :call LanguageClient#textDocument_definition()<CR>
#nnoremap F :call LanguageClient#textDocument_formatting()<CR>
#'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
hook_add = '''
call deoplete#enable()
call deoplete#custom#source('LanguageClient', 'min_pattern_length', 1)
source /home/nve3pd/.config/nvim/toml/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = """
  let g:ale_sign_error = '✘'
  let g:ale_sign_warning = '⚠'
  let g:ale_sign_column_always = 1
  let g:ale_linters = {
\   'python': ['flake8'],
\   'typescript': ['tsuquyomi'],
\}
  nmap <silent> <C-k> <Plug>(ale_previous_wrap)  # 前のエラーに
  nmap <silent> <C-j> <Plug>(ale_next_wrap)  # 次のエラーに
"""

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'itchyny/lightline.vim'
#hook_add = """
#  source /home/nve3pd/.config/nvim/toml/plugins/lightline.rc.vim
#"""

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  nnoremap <silent><C-e> :NERDTreeToggle<CR> 
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
