[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'zah/nim.vim'
on_ft = ['nim']

[[plugins]]
repo = 'nve3pd/deoplete-nim'
on_ft = ['nim']

[[plugins]]
repo = 'zchee/deoplete-jedi'
depends = ['deoplete.nvim']
on_ft = ['python']

[[plugins]]
repo = 'mhartington/nvim-typescript'
on_i = 1
on_ft = ['typescript']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_i = 1
on_ft = ['typescript']
