[[plugins]]
repo = 'zchee/deoplete-jedi'
build = 'make'
on_ft = 'python'
depends = ['deoplete.nvim']

[[plugins]]
repo = 'nve3pd/nim.vim'
on_ft = 'nim'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_post_source = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_fields = 1
  let g:go_highlight_types = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
  let g:syntastic_go_checkers = ['golint', 'govet', 'errcheck']
  let g:syntastic_mode_map = { 'mode': 'active', 'passive_filetypes': ['go'] }
"autocmd FileType go setlocal completeopt-=preview
'''

[[plugins]]
repo = 'zchee/deoplete-go'
build = 'make'
on_ft = 'go'
depends = ['deoplete.nvim']
hook_source = '''
    let g:deoplete#sources#go#gocode_binary = '/home/nve3pd/go/bin/gocode'
'''
