[[plugins]]
repo = 'ap/vim-css-color'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'mattn/vim-goimports'
on_ft = ['go']
hook_add = """
let g:goimports_simplify = 1
let g:goimports = 1
"""
